Repository FriesI23/mhabit, pull requests merged in 2025-07, with the labels that each got.

#299 Merge Weblate Translations
  assets/l10n/uk.arb
  lib/l10n/localizations_uk.g.dart
Labels: l10n

#298 Fix: dealing with unavailable getetag
  lib/extension/webdav_extensions.dart
  lib/model/_app_sync_tasks/webdav_app_sync_models.dart
Labels: bug

#292 Add documentation example for WebDAV synchronization with Nextcloud
  README.md
  docs/README/images/nextcloud-test-app-credentials.png
  docs/README/images/nextcloud-test-app-first-sync.png
  docs/README/images/nextcloud-test-app-server-config.png
  docs/README/images/nextcloud-test-app-sync-success.png
  docs/README/images/nextcloud-test-app.png
Labels: documentation

#303 fix: show UI feedback on habit deletion
  lib/component/widgets/habit_progress_indicator.dart
  lib/model/habit_summary.dart
  lib/provider/habit_detail.dart
  lib/provider/habit_summary.dart
  lib/view/common/habit_summary_list_tile.dart
  lib/view/for_habit_detail/habit_detail_summary_tile.dart
  lib/view/for_habits_display/habit_display_list_tile.dart
  lib/view/page_habit_detail.dart
Labels: bug

#305 Weblate translation
  assets/l10n/_untranslated.json
  assets/l10n/ru.arb
  lib/l10n/localizations_ru.g.dart
Labels: l10n

#311 Weblate translation
  assets/l10n/uk.arb
  lib/l10n/localizations_uk.g.dart
Labels: l10n

#313 doc: migrate wiki to main branch
  .github/workflows/publish-wiki.yml
  docs/wiki/Design꞉-WebDAV-Sync.md
  docs/wiki/Dev꞉-Build-From-Source.md
  docs/wiki/Dev꞉-Push-To-New-Version.md
  docs/wiki/Donors.md
  docs/wiki/FAQ꞉-For-Developers.md
  docs/wiki/Feature꞉WebDAV-Sync.md
  docs/wiki/Home.md
  docs/wiki/Installation.md
  docs/wiki/L10n꞉-Request-New-Language.md
  docs/wiki/_Footer.md
  docs/wiki/_Sidebar.asciidoc
  docs/wiki/images/github-release-page-01.jpg
  docs/wiki/images/webdav-sync-nextcloud/nextcloud-test-app-credentials.png
  docs/wiki/images/webdav-sync-nextcloud/nextcloud-test-app-first-sync.png
  docs/wiki/images/webdav-sync-nextcloud/nextcloud-test-app-server-config.png
  docs/wiki/images/webdav-sync-nextcloud/nextcloud-test-app-sync-success.png
  docs/wiki/images/webdav-sync-nextcloud/nextcloud-test-app.png
  docs/wiki/test/compose.yml
Labels: documentation, CI
